import 'dart:math';

List<String> questions = [
  "Name the person who had written the first worm written for computer i.e. “The Morris worm’’?",
  "Which are the two of the most commonly used languages for CGI Common Gateway Interface scripts?",
  "Which of these is not a programming language?",
  'What does the command prompt uses?',
  'Which out of the following can be called as modifiers?',
  'Which out of the following helps in quickly help you rename a file or folder?',
  'In which year did IBM developed ORTRAN High Level programming languages used to write scientific applications?',
  'Which out the following is a scripting language?',
  'What is the full of form ALU?',
  'How many way are there to carry out floating-point operation? ',
  'Which browser is provided with the latest versions of Windows 10?',
  'Which out of the following is not a GUI based operating system?',
  'Sillico Sapines is also called as what:',
  'What is a bug?',
  'What did Marcain E Huff invent?',
  'What file is used to load a config sys file?',
  'Which of the following is associated with the term like, diskpart, logon, chkdis?',
  'NTFS uses which out of the following file system?',
  'Defragmenters are used for what?',
  'What does FTP stand for?',
  "Which of the following languages are directly executable by a computer’s CPU?",
  'Which was the world’s first electronic digital programmable computer?',
  'Which of the following is the first example of an electromechanical relay computer?',
  'Who gave the first successful demonstration of use of a simplified analytical engine in computing tables in 1888?',
  'Which of the following is seen as the earliest mechanical analog computer?',
  'Which of the following comprise the software components of a computer?',
  'Which menu in MS Word can be used to change character size and typeface?',
  'Which option in File pull-down menu is used to close a file in MSWord?',
  'Graphics for word processor',
  'What is the minimum age to sign up for Facebook?',
  'Which is the part of the computer system that one can physically touch?',
  'IC chips used in computers are usually made of:',
  'Which of the following is not an input device?',
  'bit stands for'
];
List<String> option1 = [
  'Charles Alderton',
  'Perl & Java',
  'BASIC',
  'Text User Interface TUI',
  'Keys Num Lock, Backspace, and Tab',
  'F2',
  '1956',
  'Java',
  'Analyst Logic Unit',
  '2',
  'Yandex Browser',
  'Windows',
  'USB',
  'A bug is an error in a software program',
  'printer',
  'Ectomorph',
  'Erase console command',
  'File Allocation Table',
  'It is used to arrange data in order to read faster',
  'Frontside Transistor Protocol',
  'Modem',
  'Enigma',
  'Differential Analyzer',
  'Henry Babbage',
  'Astrolabe',
  'Memory',
  'View',
  'New',
  'Execute',
  'Eleven years',
  'Software',
  'Gold',
  'VDU',
  'binary information term'
];
List<String> option2 = [
  'Robert Tappan Morris Jr.',
  'C & Java',
  'BNF',
  'GUI (Graphical User Interface).',
  'Keys, Page Up , Page Down, Print SC',
  'F0',
  '1989',
  'Python',
  'Arithmetic  Logic Unit',
  '1',
  'Amigo',
  'Solaris',
  'Hardware',
  'All of the above',
  'Microprocessor',
  'Fpcbol',
  'Copy Console command',
  'Master File Table',
  'It is used to calculate sum used to check the integrity of a file.',
  'Frequency Transistor Protocol',
  'Machine Language',
  'Z2',
  'Z2',
  'Charles Babbage',
  'Planisphere',
  'BIOS',
  'Tools',
  'Close',
  'Highlight',
  'Twelve years',
  'data',
  'Chromium',
  'Keyboard',
  'Bivariate Theory'
];
List<String> option3 = [
  'George Bangs',
  'Java & C++',
  'COBOL',
  'CLI (Command Line Interface)',
  'Keys Alt, Shift, or Ctrl',
  'F8',
  '1978',
  'Lisp',
  'Algebraic Logic Unit',
  '3',
  'Safari',
  'Linux',
  'Computer',
  'A bug is a virus in the software program',
  'Scanner',
  'Dwm',
  'None',
  'Nibble File Table',
  'To copy file faster from one folder to other on same computer',
  'File Transfer Protocol',
  'Scanner',
  'Z3',
  'Torpedo Data Computer',
  'Vannevar Bush',
  'Tally Stick',
  'Programs',
  'Data',
  'Quit',
  'Peripheral',
  'Thirteen years',
  'Operating System',
  'Lead',
  'Mouse',
  'binary tree'
];
List<String> option4 = [
  'William Beldue',
  'Perl and C++',
  'FORTRAN',
  'None of the above',
  'Keys Tab, caps lock , End',
  'F9',
  '1924',
  'All of the above',
  'None of the above',
  '4',
  'Edge',
  'Plurix',
  'Operating system',
  'A bug is malware in a software program',
  'CD-ROM',
  'Pif',
  'Recovery console command',
  'New File Table',
  'bits are transferred from one location to another',
  'Floating task Protocol',
  'Printer',
  'Colossus',
  'Jacquard Loom',
  'H.W. Nieman',
  'Antikythera mechanism',
  'Keyboard',
  'Format',
  'Exit',
  'Clip art',
  'Fourteen years',
  'hardware',
  'Silicon',
  'Light Pen',
  'binary digit'
];
List<String> answers = [
  'Robert Tappan Morris Jr.',
  'Perl and C++',
  'BNF',
  'CLI (Command Line Interface)',
  'Keys Alt, Shift, or Ctrl',
  'F2',
  '1956',
  'All of the above',
  'Arithmetic  Logic Unit',
  '1',
  'Edge',
  'Plurix',
  'Computer',
  'All of the above',
  'Microprocessor',
  'Pif',
  'Recovery console command',
  'Master File Table',
  'It is used to arrange data in order to read faster',
  'File Transfer Protocol',
  'Machine Language',
  'Colossus',
  'Z2',
  'Henry Babbage',
  'Antikythera mechanism',
  'Programs',
  'Format',
  'Close',
  'Clip art',
  'Thirteen years',
  'hardware',
  'Silicon',
  'VDU',
  'binary digit'
];

List<int> amount = [
  1000,
  2000,
  5000,
  10000,
  20000,
  40000,
  80000,
  160000,
  320000,
  640000,
  1250000,
  2500000,
  5000000,
  10000000,
  30000000,
  70000000
];

//Audience Poll options
List<int> aOp1 = [
  20,
  5,
  10,
  13,
  6,
  93,
  63,
  5,
  0,
  2,
  10,
  1,
  25,
  12,
  12,
  2,
  40,
  23,
  73,
  8,
  21,
  15,
  13,
  45,
  10,
  31,
  10,
  13,
  26,
  20,
  8,
  13,
  33,
  21
];
List<int> aOp2 = [
  60,
  6,
  85,
  25,
  20,
  2,
  12,
  2,
  97,
  98,
  2,
  35,
  15,
  74,
  69,
  6,
  3,
  63,
  12,
  12,
  36,
  35,
  61,
  19,
  13,
  5,
  33,
  49,
  14,
  25,
  21,
  35,
  23,
  23
];
List<int> aOp3 = [
  5,
  16,
  3,
  58,
  60,
  1,
  10,
  4,
  1,
  0,
  25,
  12,
  56,
  3,
  8,
  21,
  2,
  4,
  8,
  74,
  30,
  12,
  6,
  4,
  34,
  54,
  21,
  15,
  10,
  28,
  9,
  9,
  30,
  11
];
List<int> aOp4 = [
  15,
  73,
  2,
  4,
  14,
  4,
  15,
  89,
  2,
  0,
  63,
  52,
  4,
  11,
  11,
  71,
  55,
  10,
  7,
  6,
  13,
  38,
  20,
  32,
  43,
  10,
  36,
  23,
  50,
  27,
  62,
  43,
  14,
  44
];

//Fifty Fifty options

List<String> fOp1 = [
  ' ',
  ' ',
  'COBOL',
  ' ',
  'Keys Tab, caps lock , End',
  'F2',
  '1956',
  ' ',
  ' ',
  '3',
  'Safari',
  ' ',
  'Hardware',
  'A bug is an error in a software program',
  ' ',
  ' ',
  'Erase console command',
  'File Allocation Table',
  'It is used to arrange data in order to read faster',
  ' ',
  ' ',
  'Z3',
  ' ',
  'Henry Babbage',
  ' ',
  'Keyboard',
  ' ',
  ' ',
  'Peripheral',
  ' ',
  ' ',
  ' ',
  'VDU',
  ' '
];
List<String> fOp2 = [
  'Robert Tappan Morris Jr.',
  ' ',
  'BNF',
  'FORTRAN',
  ' ',
  'F0',
  ' ',
  ' ',
  'Arithmetic  Logic Unit',
  '1',
  ' ',
  ' ',
  ' ',
  'All of the above',
  'Microprocessor',
  ' ',
  ' ',
  'Master File Table',
  ' ',
  'Frequency Transistor Protocol',
  'Machine Language',
  ' ',
  'Z2',
  ' ',
  ' ',
  ' ',
  'Data',
  'Close',
  ' ',
  'Twelve years',
  'Software',
  'Polythene',
  ' ',
  'binary tree'
];
List<String> fOp3 = [
  ' ',
  'Java & C++',
  '',
  'CLI (Command Line Interface)',
  'Keys Alt, Shift, or Ctrl',
  ' ',
  ' ',
  'Python',
  ' ',
  ' ',
  ' ',
  'Linux',
  'Computer',
  ' ',
  ' ',
  'Ectomorph',
  ' ',
  ' ',
  'It is used to calculate sum used to check the integrity of a file.',
  'File Transfer Protocol',
  'Printer',
  ' ',
  ' ',
  ' ',
  'Tally Stick',
  'Programs',
  ' ',
  ' ',
  ' ',
  'Thirteen years',
  ' ',
  ' ',
  'Light Pen',
  ' '
];
List<String> fOp4 = [
  'George Bangs',
  'Perl and C++',
  ' ',
  ' ',
  ' ',
  ' ',
  '1989',
  'All of the above',
  'Algebraic Logic Unit',
  ' ',
  'Edge',
  'Plurix',
  ' ',
  ' ',
  'printer',
  'Pif',
  'Recovery console command',
  ' ',
  ' ',
  ' ',
  ' ',
  'Colossus',
  'Z3',
  'H.W. Nieman',
  'Antikythera mechanism',
  ' ',
  'Format',
  'Quit',
  'Clip art',
  ' ',
  'hardware',
  'Silicon',
  ' ',
  'binary digit'
];
